export const END_USER_DEVICE_TYPES = ["DESKTOP", "LAPTOP", "ALL_IN_ONE", "OTHER"] as const;
export const INFRASTRUCTURE_DEVICE_TYPES = [
  "SERVER",
  "POE_SWITCH",
  "SWITCH_HUB",
  "LOAD_BALANCER",
  "FIREWALL",
  "ACCESS_POINT",
  "CCTV_DVR",
  "CCTV_CAMERA",
  "EXTERNAL_HDD_SSD",
  "MONITOR",
  "UPS",
  "OTHER",
] as const;

export const REFERENCE_DATA = {
  employeeStatuses: ["ACTIVE", "RESIGNED", "NEW_HIRE", "ON_LEAVE"],
  deviceTypes: [
    "DESKTOP",
    "LAPTOP",
    "ALL_IN_ONE",
    "SERVER",
    "POE_SWITCH",
    "SWITCH_HUB",
    "LOAD_BALANCER",
    "FIREWALL",
    "ACCESS_POINT",
    "CCTV_DVR",
    "CCTV_CAMERA",
    "EXTERNAL_HDD_SSD",
    "MONITOR",
    "UPS",
    "OTHER",
  ],
  endUserDeviceTypes: [...END_USER_DEVICE_TYPES],
  infrastructureDeviceTypes: [...INFRASTRUCTURE_DEVICE_TYPES],
  osLicenseStatuses: ["LICENSED", "CRACKED", "NOT_ACTIVATED", "UNKNOWN"],
  auditStatuses: ["COMPLETE", "PENDING", "INCOMPLETE"],
  assessments: ["OK_NO_ISSUES", "NEEDS_UPGRADE", "NEEDS_REPLACEMENT", "CRITICAL_IMMEDIATE_ACTION"],
  priorities: ["LOW", "MEDIUM", "HIGH", "IMMEDIATE"],
  recommendedActions: ["NO_ACTION", "UPGRADE", "REPLACE_UNIT", "SOFTWARE_REFRESH", "IMMEDIATE_REPAIR"],
  upgradeComponents: [
    "STORAGE",
    "RAM",
    "MOTHERBOARD",
    "WIFI",
    "KEYBOARD",
    "TOUCHPAD",
    "MONITOR",
    "LAPTOP_SCREEN",
    "POWER_SUPPLY",
  ],
  replacementOnlyComponents: ["NEW_LAPTOP", "NEW_DESKTOP"],
  assetStatuses: ["IN_USE", "AVAILABLE", "UNDER_REPAIR", "RESERVED", "RETIRED", "DISPOSED"],
  infrastructureAssetStatuses: ["AVAILABLE", "IN_USE", "UNDER_REPAIR", "RESERVED"],
  conditions: ["NEW", "GOOD", "FAIR", "POOR", "NON_FUNCTIONAL"],
  keyboardConditions: ["NEW", "GOOD", "FAIR", "FADING_KEYS", "FAULTY", "NEEDS_REPLACEMENT", "BUILT_IN_LAPTOP"],
  mouseTypes: ["COMPANY_PROVIDED", "PERSONAL_BYOD", "NONE"],
  screenConditions: [
    "GOOD",
    "FAIR",
    "DEAD_PIXELS",
    "FLICKERING",
    "DIM_BACKLIGHT",
    "CRACKED",
    "DISCOLORATION",
    "FAULTY",
    "NEEDS_REPLACEMENT",
  ],
  maintenanceStatuses: ["OPEN", "IN_PROGRESS", "COMPLETED", "CANCELLED"],
  disposalMethods: ["SOLD", "DONATED", "RECYCLED", "DESTROYED", "LOST", "STOLEN", "TRADE_IN", "OTHER"],
  userRoles: ["SUPER_ADMIN", "IT_ADMIN", "VIEWER"],
} as const;
